workflows:
  android-build:
    name: Android Build
    environment:
      flutter: 3.7.12
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
